kind: Service
apiVersion: v1
metadata:
  name: golang-second-echoservice
  namespace: poc-demo
  labels:
    app: golang-second-echoservice
    app.kubernetes.io/component: golang-second-echoservice
    app.kubernetes.io/instance: golang-second-echoservice
    name: golang-second-echoservice
spec:
  ports:
    - name: golang-second-echoservice
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    name: golang-second-echoservice
